language: ruby

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install -y luarocks
  - sudo luarocks install luacheck
  - rm -rf ./mods/jabber/lib

script: luacheck --no-color ./mods
