language: generic
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck
  - rm -rf ./mods/jabber/lib
script: 
- $HOME/.luarocks/bin/luacheck --no-color ./mods
